version: "3"
services:
    flask:
        build:
            context: .
        depends_on:
            - mongo
        network_mode: "host"
        ports:
            - "5000:5000"

    mongo:
        image: mongo:4.4-bionic
        restart: always
        network_mode: "host"
        ports:
            - "27017:27017"

